\documentclass{article}
\usepackage{tabularx}
\usepackage{booktabs}

\begin{document}

\renewcommand{\arraystretch}{1.8}


<<results = 'asis'>>=
devtools::load_all('.')
library(tidyverse)

tdat1 <- data.frame(
  numbers = c(1.434, 190.3, 228.311, 5.210, 4321543),
  animals = c('dog', 'cat', 'camel', 'pig', 'mouse'),
  factors = factor(c('rain', 'grain', 'stain', 'pain', 'main')),
  ints    = c(10L, 20L, 40L, 30L, 50L),
  stringsAsFactors = FALSE
)

tdat2 <- data.frame(
  numbers_xt = c(1, 290, 0.311, 0.210, 1000),
  animals_xt = c('god', 'tac', 'lemac', 'gip', 'esuom'),
  factors_xt = factor(c('tractor', 'hector', 'andrew', 'milli', 'vanilli')),
  ints    = as.character(c(5L, 5L, 10L, 30L, 25L)),
  stringsAsFactors = FALSE
)

rownames(tdat1) <- c('a', 'b', 'c', 'd', 'e')

st1 <- stack_table(tdat1, tdat2, rem_ext = '_xt')


as.data.table(st1) %>% str
as_tibble(st1)

xtable::xtable(as.data.frame(st1))

print_tex(st1)
print_tex(st1, stack_method = 'col')



@





\end{document}
